# Generated by Django 3.0.8 on 2020-08-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productsize_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='name',
        ),
    ]
