# Generated by Django 3.0.8 on 2020-08-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200827_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
    ]
