# Generated by Django 3.0.8 on 2020-09-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200905_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='name',
        ),
    ]
