# Generated by Django 3.0.8 on 2020-09-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_shippingaddress_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='state',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
