# Generated by Django 3.1.2 on 2020-10-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20201012_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
